name: client
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.2

dependencies:
  equatable: ^2.0.5
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
